export const BASE_API = "https://mapi.harmoney.dev/api";

export const ACTION_TYPES = {
  INITIALIZE_MESSAGE: "INITIALIZE_MESSAGE",
  ADD_MESSAGE: "ADD_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  SORT_ASCENDING: "SORT_ASCENDING",
  SORT_DESCENDING: "SORT_DESCENDING",
  CHANGE_PAGE: "CHANGE_PAGE"
};

export const SORT_ORDER = {
  SORT_ASCENDING: "SORT_ASCENDING",
  SORT_DESCENDING: "SORT_DESCENDING"
};

export const MAX_BOARDS = 5;
